apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinslab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinslab
  template:
    metadata:
      labels:
        app: jenkinslab
    spec:
      containers:
      - name: jenkinslab-container
        image: jenkinslab-demo:latest
        ports:
        - containerPort: 80
